### ISSUE TITLE
Set up Slack... need a name!

### ISSUE THREAD

**Issue by tgig** [tgig/Enchiridion#2]
Hi @bebelabs 

This could easily be done (and probably will be done) over text, but just so I can @mention you on an Issue, I'm doing it here as well :)

We need a name for the Slack channel. [It can be renamed later](https://slack.com/help/articles/201663443), so doesn't really matter what we call it for now. Just need a cool codename.

Any suggestions?

**Comment by tgig** [comment]
Here are a few from a random codename generator I found online

  * Mad Whisper
  * Orange Unicorn
  * Chief Beehive
  * Happy Wings

Since we're doing a Fintech-y thing, we could use some historical figure reference related to finance

  * Medici
  * Rothschild
  * Buffet
  * East India Trading
  * Hammurabi

And... [I'm spent](https://youtu.be/g_ylw4dqAD8?t=63).

**Comment by bebelabs** [comment]
Let's do Medici!  Goes with Enchiridion... which is like the knowledge base
and Medici is the father of all merchants.  I love it!

**Comment by tgig** [comment]
Done!

https://medicico.slack.com/
